-- ============================================================================
-- Migration 007: Seed network data
-- ----------------------------------------------------------------------------
-- Replaces the hardcoded setupFullPuneNetwork() station/route data that
-- previously lived in main.cpp. Generated once from that same data (not
-- hand-transcribed) to guarantee it matches exactly; main.cpp's C++ setup
-- function is removed once this migration is in place - the network loader
-- now builds the in-memory graph by reading these rows at startup.
-- ============================================================================

PRAGMA foreign_keys = ON;

-- Lines
INSERT INTO lines (line_id, name, color) VALUES (1, 'Purple', '#7F77DD');
INSERT INTO lines (line_id, name, color) VALUES (2, 'Aqua', '#378ADD');
INSERT INTO lines (line_id, name, color) VALUES (3, 'Orange', '#EF9F27');
INSERT INTO lines (line_id, name, color) VALUES (4, 'Pink', '#D4537E');

-- Stations
INSERT INTO stations (station_id, name, is_interchange) VALUES (0, 'PCMC', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (1, 'Sant Tukaram Nagar', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (2, 'Nashik Phata', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (3, 'Kasarwadi', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (4, 'Phugewadi', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (5, 'Dapodi', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (6, 'Bopodi', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (7, 'Khadki', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (8, 'Range Hill', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (9, 'Shivaji Nagar', 1);
INSERT INTO stations (station_id, name, is_interchange) VALUES (10, 'District Court', 1);
INSERT INTO stations (station_id, name, is_interchange) VALUES (11, 'Kasba Peth', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (12, 'Mahatma Phule Mandai', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (13, 'Swargate', 1);
INSERT INTO stations (station_id, name, is_interchange) VALUES (14, 'Swargate North', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (15, 'Market Yard', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (16, 'Padmavati', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (17, 'Balaji Nagar', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (18, 'Katraj', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (19, 'Chandani Chowk', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (20, 'Kothrud Bus Depot', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (21, 'Vanaz', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (22, 'Anand Nagar', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (23, 'Paud Phata', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (24, 'Nal Stop', 1);
INSERT INTO stations (station_id, name, is_interchange) VALUES (25, 'Garware College', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (26, 'Deccan Gymkhana', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (27, 'Chhatrapati Sambhaji Udyan', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (28, 'PMC', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (29, 'RTO Pune', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (30, 'Pune Railway Station', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (31, 'Ruby Hall Clinic', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (32, 'Bund Garden', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (33, 'Yerawada', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (34, 'Kalyani Nagar', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (35, 'Ramwadi', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (36, 'Viman Nagar', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (37, 'Kharadi Bypass', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (38, 'Wagholi', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (39, 'Vitthalwadi', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (40, 'Khadakwasla', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (41, 'Dalvewadi', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (42, 'Dhayari Phata', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (43, 'Manik Baug', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (44, 'Hingane Chowk', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (45, 'Rajaram Pul', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (46, 'Dandekar Pul', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (47, 'Seven Loves Chowk', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (48, 'Fatima Nagar', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (49, 'Ramtekadi', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (50, 'Hadapsar Bus Depot', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (51, 'Hadapsar', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (52, 'Magarpatta South', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (53, 'Magarpatta Main', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (54, 'Magarpatta North', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (55, 'Kharadi Chowk', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (56, 'Maan', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (57, 'Hinjawadi', 0);
INSERT INTO stations (station_id, name, is_interchange) VALUES (58, 'Baner', 0);

-- station_line (interchange stations appear once per line they sit on)
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (0, 1, 1);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (1, 1, 2);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (2, 1, 3);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (3, 1, 4);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (4, 1, 5);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (5, 1, 6);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (6, 1, 7);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (7, 1, 8);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (8, 1, 9);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (9, 1, 10);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (10, 1, 11);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (11, 1, 12);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (12, 1, 13);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (13, 1, 14);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (14, 1, 15);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (15, 1, 16);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (16, 1, 17);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (17, 1, 18);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (18, 1, 19);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (19, 2, 1);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (20, 2, 2);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (21, 2, 3);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (22, 2, 4);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (23, 2, 5);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (24, 2, 6);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (25, 2, 7);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (26, 2, 8);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (27, 2, 9);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (28, 2, 10);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (10, 2, 11);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (29, 2, 12);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (30, 2, 13);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (31, 2, 14);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (32, 2, 15);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (33, 2, 16);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (34, 2, 17);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (35, 2, 18);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (36, 2, 19);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (37, 2, 20);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (38, 2, 21);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (39, 2, 22);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (40, 3, 1);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (41, 3, 2);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (42, 3, 3);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (43, 3, 4);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (44, 3, 5);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (45, 3, 6);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (24, 3, 7);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (46, 3, 8);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (13, 3, 9);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (47, 3, 10);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (48, 3, 11);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (49, 3, 12);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (50, 3, 13);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (51, 3, 14);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (52, 3, 15);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (53, 3, 16);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (54, 3, 17);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (55, 3, 18);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (56, 4, 1);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (57, 4, 2);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (58, 4, 3);
INSERT INTO station_line (station_id, line_id, sequence_number) VALUES (9, 4, 4);

-- Routes (station_a_id < station_b_id enforced by schema)
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (1, 1, 0, 1, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (2, 1, 1, 2, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (3, 1, 2, 3, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (4, 1, 3, 4, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (5, 1, 4, 5, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (6, 1, 5, 6, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (7, 1, 6, 7, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (8, 1, 7, 8, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (9, 1, 8, 9, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (10, 1, 9, 10, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (11, 1, 10, 11, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (12, 1, 11, 12, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (13, 1, 12, 13, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (14, 1, 13, 14, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (15, 1, 14, 15, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (16, 1, 15, 16, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (17, 1, 16, 17, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (18, 1, 17, 18, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (19, 2, 19, 20, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (20, 2, 20, 21, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (21, 2, 21, 22, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (22, 2, 22, 23, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (23, 2, 23, 24, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (24, 2, 24, 25, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (25, 2, 25, 26, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (26, 2, 26, 27, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (27, 2, 27, 28, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (28, 2, 10, 28, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (29, 2, 10, 29, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (30, 2, 29, 30, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (31, 2, 30, 31, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (32, 2, 31, 32, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (33, 2, 32, 33, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (34, 2, 33, 34, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (35, 2, 34, 35, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (36, 2, 35, 36, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (37, 2, 36, 37, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (38, 2, 37, 38, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (39, 2, 38, 39, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (40, 3, 40, 41, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (41, 3, 41, 42, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (42, 3, 42, 43, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (43, 3, 43, 44, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (44, 3, 44, 45, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (45, 3, 24, 45, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (46, 3, 24, 46, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (47, 3, 13, 46, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (48, 3, 13, 47, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (49, 3, 47, 48, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (50, 3, 48, 49, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (51, 3, 49, 50, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (52, 3, 50, 51, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (53, 3, 51, 52, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (54, 3, 52, 53, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (55, 3, 53, 54, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (56, 3, 54, 55, 2.5, 1.2);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (57, 4, 56, 57, 5.0, 3.0);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (58, 4, 57, 58, 8.0, 5.0);
INSERT INTO routes (route_id, line_id, station_a_id, station_b_id, time_minutes, distance_km) VALUES (59, 4, 9, 58, 6.0, 4.0);